"""Raw CAN MF4 import: adapter, recovery, pipeline and API.

Fixtures are generated by ``mf4_fixture`` with the layout of the third-party
logger behind the external sample (single DT, one-byte record IDs, virtual
bus/direction/IDE channels, and -- when unfinished -- an ``UnFinMF`` header with
zero cycle counters and a header-only last DT). The operational recording itself
is never needed in CI.
"""

from __future__ import annotations

import hashlib
import tempfile
from pathlib import Path

import pytest
from mf4_fixture import Group, Record, write_mf4
from starlette.testclient import TestClient

from cantracediag.formats.mf4 import Mf4ImportError, parse_mf4, stream_mf4
from cantracediag.models import NonDataEvent, RawCanFrame
from cantracediag.pipeline import ImportCancelled, import_trace

# asammdf's MDF4.__del__ raises AttributeError after a failed open; harmless.
pytestmark = pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")

FIX = Path(__file__).parent / "fixtures"
DBC = FIX / "sample.dbc"

GROUPS = [
    Group("CAN9_Rx", 32, constants={"BusChannel": 9, "IDE": 0, "Dir": 0}),
    Group("CAN1_Rx", 64, constants={"BusChannel": 1, "IDE": 0, "Dir": 0}),
    Group("CAN1_Tx_IDE", 67, constants={"BusChannel": 1, "IDE": 1, "Dir": 1}),
    Group("CAN2_Mixed", 70, stored=("BusChannel", "Dir", "IDE", "EDL")),
    Group("CAN1_RTR", 80, kind="remote", constants={"BusChannel": 1, "IDE": 0, "Dir": 0}),
    Group("CAN1_Errors", 90, kind="error", constants={"BusChannel": 1}),
    Group("LIN1_Frame", 100, kind="lin", constants={"BusChannel": 1}),
    # Declared but never populated, like the sample's FD/LIN schema groups.
    Group("CAN1_Rx_FD", 110, constants={"BusChannel": 1, "IDE": 0, "Dir": 0, "EDL": 1}),
]

ENGINE = bytes([0x40, 0x1F, 0x5A, 0, 0, 0, 0, 0])  # EngineSpeed 2000 rpm, 50 degC

RECORDS = [
    Record("CAN1_Rx", 0.5, 0x100, 8, ENGINE),
    Record("CAN9_Rx", 1.0, 0x7FF, 0, b""),
    Record("CAN1_Rx", 1.0, 0x123, 8, bytes(range(8))),  # same time, later group
    Record("CAN1_Tx_IDE", 1.5, 0x18FF00AA, 2, b"\x01\x02"),
    Record("CAN2_Mixed", 2.0, 0x200, 2, b"\x10\x27",
           values={"BusChannel": 2, "Dir": 1, "IDE": 0, "EDL": 0}),
    Record("CAN2_Mixed", 2.0, 0x101, 8, b"x" * 8,
           values={"BusChannel": 2, "Dir": 0, "IDE": 0, "EDL": 1}),
    Record("CAN1_RTR", 2.5, 0x55, 4),
    Record("CAN1_Errors", 3.0),
    Record("LIN1_Frame", 3.5, 0x10, 2, b"zz"),
    Record("CAN1_Rx", 4.0, 0x124, 9, b"y" * 8),  # classic DLC out of range
    Record("CAN1_Rx", 4.5, 0x125, 8, b"z" * 8, length=7),  # DataLength != DLC
    Record("CAN1_Rx", 5.0, 0x100, 8, ENGINE),
]


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.fixture(params=[False, True], ids=["finalized", "unfinished"])
def mf4(request, tmp_path: Path) -> Path:
    return write_mf4(tmp_path / "trace.mf4", GROUPS, RECORDS, unfinished=request.param)


@pytest.fixture
def unfinished(tmp_path: Path) -> Path:
    return write_mf4(tmp_path / "00000002.MF4", GROUPS, RECORDS, unfinished=True)


# -- adapter ----------------------------------------------------------------
def test_raw_frames_are_normalized_without_a_dbc(mf4: Path) -> None:
    frames = parse_mf4(mf4).frames

    assert [(f.timestamp_s, f.channel, f.arbitration_id, f.is_extended_id) for f in frames] == [
        (0.5, "1", 0x100, False),
        (1.0, "9", 0x7FF, False),
        (1.0, "1", 0x123, False),
        (1.5, "1", 0x18FF00AA, True),
        (2.0, "2", 0x200, False),
        (5.0, "1", 0x100, False),
    ]
    assert frames[1].dlc == 0 and frames[1].data == b""
    assert frames[2].data == bytes(range(8))
    assert [f.direction for f in frames] == ["Rx", "Rx", "Rx", "Tx", "Tx", "Rx"]
    assert all(f.message_name is None and not f.is_remote for f in frames)


def test_unsupported_and_malformed_records_are_diagnosed_not_dropped(mf4: Path) -> None:
    events = parse_mf4(mf4).events

    assert [(e.timestamp_s, e.event_type) for e in events] == [
        (2.0, "Mf4Unsupported"),
        (2.5, "Mf4RemoteRequest"),
        (3.0, "ErrorFrame"),
        (3.5, "Mf4Skipped"),
        (4.0, "Mf4Anomaly"),
        (4.5, "Mf4Anomaly"),
    ]
    assert "LIN1_Frame" in events[3].detail
    assert "DLC 9" in events[4].detail
    assert "data length 7" in events[5].detail


def test_unfinished_and_finalized_layouts_read_identically(tmp_path: Path) -> None:
    final = parse_mf4(write_mf4(tmp_path / "a.mf4", GROUPS, RECORDS))
    unfin = parse_mf4(write_mf4(tmp_path / "b.mf4", GROUPS, RECORDS, unfinished=True))

    assert final.frames == unfin.frames
    assert final.events == unfin.events
    assert unfin.record_count == len(RECORDS)


def test_zero_cycle_counters_never_produce_an_empty_import(unfinished: Path) -> None:
    scanner, items = stream_mf4(unfinished)
    frames = [i for i in items if isinstance(i, RawCanFrame)]

    assert len(frames) == 6
    assert scanner.recovered
    assert any("unfinalized" in w for w in scanner.warnings)


def test_recovery_never_modifies_the_source(unfinished: Path, tmp_path: Path,
                                            monkeypatch) -> None:
    before = _sha(unfinished)
    stamp = unfinished.stat().st_mtime_ns
    monkeypatch.setattr(tempfile, "tempdir", str(tmp_path / "tmp"))
    (tmp_path / "tmp").mkdir()

    parse_mf4(unfinished)

    assert _sha(unfinished) == before
    assert unfinished.stat().st_mtime_ns == stamp
    # The disposable recovery copy is removed again.
    assert list((tmp_path / "tmp").iterdir()) == []


def test_groups_merge_chronologically_with_documented_ties(tmp_path: Path) -> None:
    records = [
        Record("CAN9_Rx", 0.5, 0x4, 1, b"d"),
        Record("CAN1_Rx", 1.0, 0x1, 1, b"a"),
        Record("CAN9_Rx", 1.0, 0x2, 1, b"b"),
        Record("CAN1_Rx", 1.0, 0x3, 1, b"c"),
        Record("CAN1_Rx", 1.25, 0x5, 1, b"e"),
    ]
    frames = parse_mf4(write_mf4(tmp_path / "t.mf4", GROUPS, records)).frames

    # Time first; equal times by group order in the file (CAN9_Rx is group 0),
    # then by record order within the group. Timestamps are not rebased.
    assert [f.arbitration_id for f in frames] == [0x4, 0x2, 0x1, 0x3, 0x5]
    assert [f.timestamp_s for f in frames] == [0.5, 1.0, 1.0, 1.0, 1.25]


def test_time_going_backwards_in_a_group_is_reported(tmp_path: Path) -> None:
    records = [Record("CAN1_Rx", 1.0, 0x1, 1, b"a"), Record("CAN1_Rx", 0.5, 0x2, 1, b"b")]
    store, result = import_trace(write_mf4(tmp_path / "t.mf4", GROUPS, records))

    assert result.summary["frames"] == 2
    assert any("backwards" in w for w in result.summary["warnings"])
    rows = store.trace_rows(limit=10)["rows"]
    assert [r["timestamp_s"] for r in rows] == [0.5, 1.0]
    store.close()


def test_chunked_reading_matches_a_single_read(tmp_path: Path) -> None:
    records = [
        Record("CAN1_Rx" if i % 3 else "CAN9_Rx", i * 0.001, i % 0x7FF, 8, bytes([i % 256] * 8))
        for i in range(500)
    ]
    path = write_mf4(tmp_path / "t.mf4", GROUPS, records, unfinished=True)

    _s, whole = stream_mf4(path, chunk_records=100_000)
    _s, chunked = stream_mf4(path, chunk_records=7)
    assert list(chunked) == list(whole)


def test_missing_provenance_stays_unknown(tmp_path: Path) -> None:
    groups = [Group("Anon", 1, stored=())]  # no BusChannel, Dir or IDE channels
    records = [Record("Anon", 0.1, 0x7FF, 1, b"a"), Record("Anon", 0.2, 0x80000123, 1, b"b"),
               Record("Anon", 0.3, 0x800, 1, b"c")]
    frames = parse_mf4(write_mf4(tmp_path / "t.mf4", groups, records)).frames

    assert [f.channel for f in frames] == [None, None, None]
    assert [f.direction for f in frames] == [None, None, None]
    # Without IDE: bit 31 or an id above 0x7FF marks the frame extended.
    assert [(f.arbitration_id, f.is_extended_id) for f in frames] == [
        (0x7FF, False), (0x123, True), (0x800, True)
    ]


def test_a_group_without_mandatory_children_is_skipped_with_a_diagnostic(
    tmp_path: Path,
) -> None:
    groups = [Group("NoBytes", 1, constants={"BusChannel": 1}, omit=("DataBytes",))]
    result = parse_mf4(write_mf4(tmp_path / "t.mf4", groups, [Record("NoBytes", 1.0, 1, 1)]))

    assert result.frames == []
    assert [e.event_type for e in result.events] == ["Mf4Skipped"]


def test_an_empty_measurement_is_a_valid_empty_import(tmp_path: Path) -> None:
    for unf in (False, True):
        result = parse_mf4(write_mf4(tmp_path / f"e{unf}.mf4", GROUPS, [], unfinished=unf))
        assert result.frames == [] and result.events == []


@pytest.mark.parametrize("unf", [False, True], ids=["finalized", "unfinished"])
def test_a_truncated_recording_fails_before_yielding_anything(tmp_path: Path, unf) -> None:
    path = write_mf4(tmp_path / "t.mf4", GROUPS, RECORDS, unfinished=unf, truncate=5)
    _scanner, items = stream_mf4(path)

    # Unfinished: the reconciliation catches it. Finalized: the declared DT
    # length runs past end of file and asammdf refuses the container.
    with pytest.raises(Mf4ImportError, match="truncated|not a readable|Not a readable"):
        next(items)


def test_payload_that_mimics_a_block_header_cannot_shorten_recovery(tmp_path: Path) -> None:
    records = [Record("CAN1_Rx", i * 0.01, 0x100 + i, 8, bytes(8)) for i in range(64)]
    path = write_mf4(tmp_path / "t.mf4", GROUPS, records, unfinished=True,
                     spoof_signature=True)

    # asammdf locates the end of the stale DT by scanning for block signatures;
    # the independent reconciliation refuses the shortened result.
    with pytest.raises(Mf4ImportError, match="data bytes"):
        parse_mf4(path)


@pytest.mark.parametrize(
    "content",
    [b"", b"not an mdf file at all" * 4, b"MDF     3.30    " + b"\0" * 48],
    ids=["empty", "garbage", "mdf3"],
)
def test_non_mf4_content_is_rejected(tmp_path: Path, content: bytes) -> None:
    path = tmp_path / "bad.mf4"
    path.write_bytes(content)

    with pytest.raises(Mf4ImportError):
        parse_mf4(path)


def test_cancellation_during_initialization(unfinished: Path, tmp_path: Path,
                                            monkeypatch) -> None:
    calls = {"n": 0}

    def cancel() -> bool:
        calls["n"] += 1
        return calls["n"] >= 2  # first poll passes, the open/recovery hook cancels

    monkeypatch.setattr(tempfile, "tempdir", str(tmp_path / "tmp"))
    (tmp_path / "tmp").mkdir()
    _s, items = stream_mf4(unfinished, cancel_check=cancel)
    with pytest.raises(ImportCancelled):
        next(items)
    assert list((tmp_path / "tmp").iterdir()) == []


def test_cancellation_during_record_ingestion(tmp_path: Path) -> None:
    records = [Record("CAN1_Rx", i * 0.001, 0x100, 8, ENGINE) for i in range(300)]
    path = write_mf4(tmp_path / "t.mf4", GROUPS, records)
    seen = {"items": 0}

    def cancel() -> bool:
        return seen["items"] >= 50

    _s, items = stream_mf4(path, cancel_check=cancel, chunk_records=20)
    with pytest.raises(ImportCancelled):
        for _ in items:
            seen["items"] += 1
    assert 50 <= seen["items"] < 300


# -- pipeline ---------------------------------------------------------------
def test_mf4_frames_decode_against_the_shared_dbc_decoder(mf4: Path) -> None:
    store, result = import_trace(mf4, [DBC], decode_samples=True)

    assert result.summary["frames"] == 6
    assert result.summary["events"] == 6
    series = store.signal_series("EngineData", "EngineSpeed")
    assert series["v"] == [2000.0, 2000.0]
    assert series["t"] == [0.5, 5.0]
    store.close()


def test_mf4_import_without_dbc_keeps_every_frame(unfinished: Path) -> None:
    store, result = import_trace(unfinished)

    assert result.summary["frames"] == 6
    assert result.summary["decoded_frames"] == 0
    assert any("unfinalized" in w for w in result.summary["warnings"])
    store.close()


def test_mf4_import_reports_monotonic_progress(tmp_path: Path) -> None:
    records = [Record("CAN1_Rx", i * 0.001, 0x100, 8, ENGINE) for i in range(12_000)]
    fractions: list[float] = []
    store, _ = import_trace(write_mf4(tmp_path / "t.mf4", GROUPS, records),
                            on_progress=fractions.append)

    assert fractions == sorted(fractions)
    assert len(fractions) >= 3
    assert fractions[-1] == 1.0
    store.close()


def test_mf4_import_honours_cancellation(unfinished: Path) -> None:
    with pytest.raises(ImportCancelled):
        import_trace(unfinished, cancel_check=lambda: True)


def test_items_are_normalized_project_models(mf4: Path) -> None:
    _s, items = stream_mf4(mf4)
    assert all(isinstance(i, RawCanFrame | NonDataEvent) for i in items)


# -- API --------------------------------------------------------------------
def test_upload_accepts_an_upper_case_mf4(client: TestClient, unfinished: Path) -> None:
    r = client.post(
        "/api/import-files",
        files=[
            ("trace", ("00000002.MF4", unfinished.read_bytes(), "application/octet-stream")),
            ("dbcs", ("sample.dbc", DBC.read_bytes(), "application/octet-stream")),
        ],
    )

    assert r.status_code == 200
    body = r.json()
    assert body["summary"]["frames"] == 6
    assert any("unfinalized" in w for w in body["summary"]["warnings"])
    assert client.get("/api/trace", params={"limit": 100}).json()["total"] == 12


def test_path_import_accepts_an_mf4(client: TestClient, mf4: Path) -> None:
    r = client.post("/api/import", json={"trace_path": str(mf4), "dbc_paths": [str(DBC)]})

    assert r.status_code == 200
    assert r.json()["summary"]["frames"] == 6
    report = client.get("/api/report").json()
    assert report["anomalies"]["asc_events"]["Mf4Anomaly"] == 2


def test_a_truncated_mf4_upload_keeps_the_loaded_trace(client: TestClient,
                                                       tmp_path: Path) -> None:
    ok = client.post("/api/import", json={"trace_path": str(FIX / "sample.asc"),
                                          "dbc_paths": [str(DBC)]})
    assert ok.status_code == 200
    bad = write_mf4(tmp_path / "cut.mf4", GROUPS, RECORDS, unfinished=True, truncate=3)

    r = client.post(
        "/api/import-files",
        files=[("trace", ("cut.mf4", bad.read_bytes(), "application/octet-stream"))],
    )

    assert r.status_code == 422
    assert "MF4 import failed" in r.json()["detail"]
    assert str(tmp_path) not in r.text
    assert client.get("/api/status").json()["summary"]["frames"] == 6
    assert client.get("/api/import-job").json()["phase"] == "failed"
